{
 "title": "MLT Dashboard",
 "tags": [
  "intro-to-mlt",
  "mythical-beasts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "httpStatus",
    "label": "HTTP Status",
    "query": {}
   },
   {
    "name": "httpEndpoint",
    "label": "HTTP Endpoint",
    "query": {}
   },
   {
    "name": "serviceVersion",
    "label": "Service Version",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate edited from git",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (http_target)(rate(traces_spanmetrics_latency_sum{http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m]))) / (sum by (http_target)(rate(traces_spanmetrics_latency_count{http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m])))"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m]))/sum(increase(traces_spanmetrics_calls_total{status_code!=\"\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m])))/(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code!=\"\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "HTTP Status codes by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (http_status_code,http_target,service_version)(increase(traces_spanmetrics_calls_total{http_status_code=~\"${httpStatus}\",http_target=~\"${httpEndpoint}\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (http_method,http_target,service_version)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[10m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mythical_request_times_bucket[$__rate_interval])) by (le, beast))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{job=\"alloy\"} | logfmt | status=\"Error\""
    }
   ]
  }
 ]
}